name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronized ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Run unit tests
        run: mvn test

      - name: Update project code
        run: |
          git add --all
          git commit -m "Update project code"
          git push origin main

  deploy:
    needs: build
    if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: mvn install

      - name: Create project build
        run: mvn package

      - name: Deploy to server
        run: scp target/*.war username@server_ip:/path/to/deploy/directory

      - name: Verify deployment
        run: ssh username@server_ip 'tail -1 /path/to/server.log'
